"""
Default configuration of the bot

DO NOT EDIT THIS FILE to configure your instance of the bot, instead edit `/settings.py`.
"""

# ----------------------------------------------------------------------------------------------------------------------
# Internationalisation
#
# The official documentation suggests that bots should switch to the user's language or fall back to English.  This is
# not completely adequate for this bot that is designed for groups of nationals; the default English may be not optimal.
# The settings below define the "standard" behaviour suggested by the documentation, but may be overridden in settings.py.
#
# Whether the bot should try to switch to the user's language
SPEAK_USER_LANGUAGE = True
# Language to fall back to if there is no translation to the user's language
DEFAULT_LANGUAGE = "en"
# Supported languages.  Must be a subset of languages that present in the `locales` directory.
SUPPORTED_LANGUAGES = ("en", "ru")

# ----------------------------------------------------------------------------------------------------------------------
# Bot personality
#
# Bot name may imply its "gender" that affects "personal" messages (like "I am the host" vs. "I am the hostess").  This
# setting tells which one to pick.
BOT_IS_MALE = False

# ----------------------------------------------------------------------------------------------------------------------
# Greeting new users
#
# The bot can reply to each service message about a new user joining the group.  These bot replies can be deleted by the
# bot after the specified delay.
#
# Whether to greet users that join the group
GREETING_ENABLED = True
# Delay in seconds for deleting the greeting, 0 for not deleting the greetings
GREETING_TIMEOUT = 300

# ----------------------------------------------------------------------------------------------------------------------
# Moderation
#
# The bot may ask the moderators to approve changes made by users to their data records.
#
# Whether moderation is enabled
MODERATION_ENABLED = True
# Whether moderation is "lazy" (True) or "mandatory" (False)
MODERATION_IS_LAZY = True
# Telegram IDs of moderators
MODERATOR_IDS = tuple()

# ----------------------------------------------------------------------------------------------------------------------
# Language moderation
#
# The bot may ask people in the main chat to speak the default language.  If the bot detects too many messages written
# in languages other than the default one, it posts a message that reminds the people about rules of the group.
#
# Whether bot controls languages
LANGUAGE_MODERATION_ENABLED = False
#
# Maximum number of languages in non-default language
LANGUAGE_MODERATION_MAX_FOREIGN_MESSAGE_COUNT = 3
#
# Minimum number of words in a message that the bot should evaluate when detecting the language
LANGUAGE_MODERATION_MIN_WORD_COUNT = 3

# ----------------------------------------------------------------------------------------------------------------------
# Antispam
#
# The bot may detect and delete spam messages.  Spammers in Telegram are normally regular users that join the group, sit
# silent for some time, and then send their junk, hoping that someone will see and buy it before the moderators react.
# Telegram blocks user accounts that have been reported as spammers, which makes it not worth it trying to mimic the
# good user before sending spam.  Therefore, to eliminate most spam, it should be enough to evaluate the first message a
# new user sends to the group.
#
# Whether the feature is enabled
ANTISPAM_ENABLED = False
# Whether to use simple filter that triggers on a single word
ANTISPAM_STOP_WORDS_ENABLED = False
# Whether to use OpenAI-backed filter
ANTISPAM_OPENAI_ENABLED = False
# Whether to use OpenAI-backed filter
ANTISPAM_OPENAI_API_KEY = ""

# ----------------------------------------------------------------------------------------------------------------------
# General settings
#
# Generic delay in seconds for self-destructing messages
DELETE_MESSAGE_TIMEOUT = 60
