"""
Default configuration of the bot

DO NOT EDIT THIS FILE to configure your instance of the bot, instead edit `/settings.py`.
"""

# ----------------------------------------------------------------------------------------------------------------------
# Internationalisation
#
# The official documentation suggests that bots should switch to the user's language or fall back to English.  This is
# not completely adequate for this bot that is designed for groups where certain language may be desirable by most
# users, and the default English may be not optimal.
#
# The settings below define the "standard" behaviour suggested by the Telegram documentation, but may be overridden in
# settings.py.
#
# Whether the bot should try to switch to the user's language.  Default is True.
SPEAK_USER_LANGUAGE = True
# Language to fall back to if there is no translation to the user's language. Default is "en".
DEFAULT_LANGUAGE = "en"
# Supported languages.  Must be a subset of languages that present in the `locales` directory.  Default is a tuple that
# contains all available languages.
SUPPORTED_LANGUAGES = ("en", "ru")

# ----------------------------------------------------------------------------------------------------------------------
# Bot personality
#
# Bot name may imply its "gender" that affects "personal" messages (like "I am the host" vs. "I am the hostess").  This
# setting tells which one to pick.  Default is False.
BOT_IS_MALE = False

# ----------------------------------------------------------------------------------------------------------------------
# User directory settings
#
# The core function of this bot is to keep records submitted by users, and to render the list of those records at
# request.  The more users register themselves with the bot, the longer the list becomes, and at some moment it may
# exceed the limit that Telegram has for message size.  Should that happen, the bot will switch to two-step mode when
# displaying the user directory: first only the list of categories will be rendered, and the user will then select a
# category and get the list of users in that category.
#
# Maximum length of a message that the bot should send to the users.  Default is 4096, which is the hard limit at the
# server side.
MAX_MESSAGE_LENGTH = 4096
# Whether to force two-step mode always.  Default is False.
SHOW_CATEGORIES_ALWAYS = False

# ----------------------------------------------------------------------------------------------------------------------
# Greeting new users
#
# The bot can reply to each service message about a new user joining the group.  These bot replies can be deleted by the
# bot after the specified delay.
#
# Whether to greet users that join the group.  Default is True.
GREETING_ENABLED = True
# Delay in seconds for deleting the greeting, 0 for not deleting the greetings.  Default is 300.
GREETING_TIMEOUT = 300

# ----------------------------------------------------------------------------------------------------------------------
# Moderation
#
# The bot may ask the moderators to approve changes made by users to their data records.
#
# Whether moderation is enabled.  Default is True.
MODERATION_ENABLED = True
# Whether moderation is "lazy" (True) or "mandatory" (False).  Default is True.
MODERATION_IS_LAZY = True

# ----------------------------------------------------------------------------------------------------------------------
# Language moderation
#
# The bot may ask people in the main chat to speak the default language.  If the bot detects too many messages written
# in languages other than the default one, it posts a message that reminds the people about rules of the group.
#
# Whether bot controls languages.  Default is False.
LANGUAGE_MODERATION_ENABLED = False
#
# Maximum number of languages in non-default language.  Default is 3.
LANGUAGE_MODERATION_MAX_FOREIGN_MESSAGE_COUNT = 3
#
# Minimum number of words in a message that the bot should evaluate when detecting the language.  Default is 3.
LANGUAGE_MODERATION_MIN_WORD_COUNT = 3

# ----------------------------------------------------------------------------------------------------------------------
# Antispam
#
# The bot may detect and delete spam messages.  Spammers in Telegram are normally regular users that join the group, sit
# silent for some time, and then send their junk, hoping that someone will see and buy it before the moderators react.
# Telegram blocks user accounts that have been reported as spammers, which makes it not worth it trying to mimic the
# good user before sending spam.  Therefore, to eliminate most spam, it should be enough to evaluate the first message a
# new user sends to the group.
#
# List of layers of spam detection.  Default is empty.
ANTISPAM_ENABLED = tuple()
# Maximum number of custom emojis in a message.  Default is 5.
ANTISPAM_EMOJIS_MAX_CUSTOM_EMOJI_COUNT = 5
# API key for the OpenAI-backed filter (the openai layer).  Mandatory for that layer if it is enabled.
ANTISPAM_OPENAI_API_KEY = ""
# Confidence threshold for the OpenAI model.  Default is 0.5.
ANTISPAM_OPENAI_CONFIDENCE_THRESHOLD = 0.5

# ----------------------------------------------------------------------------------------------------------------------
# General settings
#
# Generic delay in seconds for self-destructing messages.  Default is 60.
DELETE_MESSAGE_TIMEOUT = 60

# Administrators (key is Telegram ID and value is Telegram username)
ADMINISTRATORS = dict()
