"""
Constants used in commands and conversation graphs
"""

COMMAND_WHO, COMMAND_ENROLL, COMMAND_UPDATE, COMMAND_RETIRE = ("who", "update", "enroll", "retire")
SELECTING_CATEGORY, TYPING_OCCUPATION, TYPING_DESCRIPTION, TYPING_LOCATION, CONFIRMING_LEGALITY = range(5)
RESPONSE_YES, RESPONSE_NO = ("yes", "no")
MODERATOR_APPROVE, MODERATOR_DECLINE = ("approve", "decline")
