"""
Helper functions and constants used in tests
"""

import datetime
from collections.abc import Iterator
from unittest.mock import patch

from telegram import User

from common.settings import settings
from features.services import state

CATEGORY_1_ID = 1
CATEGORY_1_TITLE = "Category 1"

CATEGORY_2_ID = 2
CATEGORY_2_TITLE = "Category 2"

SERVICE_101_TG_ID = 101
SERVICE_101_CATEGORY_ID = CATEGORY_1_ID


def return_single_category(*_args, **_kwargs) -> Iterator[dict]:
    yield data_row_for_service_category(CATEGORY_1_ID)


def return_two_categories(*_args, **_kwargs) -> Iterator[dict]:
    yield data_row_for_service_category(CATEGORY_1_ID)
    yield data_row_for_service_category(CATEGORY_2_ID)


def return_no_categories(*_args, **_kwargs) -> Iterator[dict]:
    yield from ()


def test_tg_username(tg_id: int) -> str:
    return f"username_{tg_id}"


def test_tg_first_name(tg_id: int) -> str:
    return f"Firstname_{tg_id}"


def test_occupation(tg_id: int) -> str:
    return f"Occupation {tg_id}"


def test_description(tg_id: int) -> str:
    return f"Description {tg_id}"


def test_location(tg_id: int) -> str:
    return f"Location {tg_id}"


def test_is_suspended(tg_id: int) -> bool:
    return tg_id % 2 == 1


def test_category_title(category_id: int) -> str:
    return f"Category {category_id}"


def test_last_modified(tg_id: int) -> datetime:
    return datetime.datetime.fromisoformat("2026-01-14 12:00:00") - datetime.timedelta(days=tg_id)


def test_username_to_tg_id(tg_username: str) -> int:
    """Deduces a test Telegram ID from a test-generated Telegram username

    @param tg_username: test username generated previously by a call to tg_username()
    @return: ID part of the username converted to int
    """
    return int(tg_username.split("_")[-1])


def create_test_user(tg_id: int) -> User:
    return User(id=tg_id, first_name=test_tg_first_name(tg_id), is_bot=False, username=test_tg_username(tg_id),
                language_code=settings.DEFAULT_LANGUAGE)


def data_row_for_service(tg_id: int, category_id: int) -> dict:
    """Return a dict sufficient to create a Service object with the given IDs

    @param tg_id: Telegram ID of the owner of the service
    @param category_id: ID of the category the service belongs to
    @return: dictionary that contains generated test values for all data fields necessary to construct a Service object
    """

    return {"tg_id": tg_id, "tg_username": test_tg_username(tg_id), "category_id": category_id,
            "occupation": test_occupation(tg_id), "description": test_description(tg_id), "location": test_location(tg_id),
            "is_suspended": test_is_suspended(tg_id), "last_modified": test_last_modified(tg_id)}


def data_row_for_service_category(category_id: int) -> dict:
    """Return a dict sufficient to create a ServiceCategory object with the given ID

    @param category_id: ID of the service category
    @return: dictionary that contains generated test values for all data fields necessary to construct a
    ServiceCategory object
    """

    return {"id": category_id, "title": test_category_title(category_id)}


def patch_service_get_all_by_user_return_nothing():
    """Patch features.services.state._service_get_all_by_user so that it would return an empty sequence

    @return: Context manager returned from a call to unittest.mock.patch()
    """

    def return_no_services(_tg_id: int) -> Iterator[dict]:
        yield from ()

    return patch("features.services.state._service_get_all_by_user", return_no_services)


def load_test_categories(category_count: int) -> None:
    """Load `category_count` test categories

    @param category_count:
    @return: none

    Resets the cache in the `ServiceCategory` class so that it would have `category_count` categories.  The objects
    have consecutive IDs in range [1, `category_count`] and titles generated by `test_category_title()`.
    """
    def return_n_categories(*_args, **_kwargs) -> Iterator[dict]:
        for category_id in range(1, category_count + 1):
            yield data_row_for_service_category(category_id)

    with patch("features.services.state._service_category_select_all", return_n_categories):
        state.ServiceCategory.load()
