"""
Constants used across the module
"""

ACTION_WARN, ACTION_RESTRICT, ACTION_BAN = "warn", "restrict", "ban"

MODERATION_REASON_COUNT = 5

(MODERATION_REASON_FRAUD, MODERATION_REASON_OFFENSE, MODERATION_REASON_RACISM, MODERATION_REASON_SPAM,
 MODERATION_REASON_TOXIC) = range(MODERATION_REASON_COUNT)
MODERATION_REASON_CANCEL = -1
